# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CASL
email: arpith.k@csa.iisc.ernet.in

tagline:      'Computer Architecture and Systems Lab'
description:  'Computer Architecture and Systems Lab'

# the base hostname & protocol for your site
# do not put `/` at the wnd of url
url: "http://127.0.0.1:4000" 


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

author:
  name:           'Arpith K'
  url:            http://arpith.xyz