- name: Rupesh Wani
  id: rupeshwani88
  domain: gmail.com
  research: 
  homepage: javascript:void(0)
  image: default-profile.png

- name: Vivek Shikaripura 
  id: vivek.shikaripura
  domain: gmail.com
  research: 
  homepage: javascript:void(0)
  image: default-profile.png