- name: Rupesh Wani
  id: rupeshwani88
  domain: gmail.com
  research: Operating System Security and Verification
  homepage: javascript:void(0)
  image: rupesh.jpg

- name: Vivek Shikaripura 
  id: vivek.shikaripura
  domain: gmail.com
  research: 
  homepage: javascript:void(0)
  image: default-profile.png
